import { Box, Heading } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import { Text } from "@chakra-ui/react";
import CarouselSlide from '../components/CarouselSlide'
import AboutUs from '../components/AboutUs'
import OurServices from '../components/OurServices'
import DrawerMenu from '../components/DrawerMenu'
import WhoAreWe from '../components/WhoAreWe'
import WhatWeDo from '../components/WhatWeDo'
import SocialMediaMarketing from '../components/SocialMediaMarketing'
import BreakDesign from '../components/BreakDesign'
import GraphicDesign from '../components/GraphicDesign'
import WebDesign from '../components/WebDesign'
import Seo from '../components/Seo'
import ContactUs from '../components/ContactUs'
import Experience from '../components/Experience'
import Icons from '../components/Icons'

export default function Home() {
  return (
    <Box className={styles.container}
    style={{
      backgroundImage: `url(bg3.jpg)`,
      width: '100%',
      // height: '100%',
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
      backgroundAttachment:'fixed'
  
    }}
   >
      <Head>
        <title>Digital marketing</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <Icons/> */}
       <Navbar /> 
       <WhoAreWe/>
       <WhatWeDo/>
       <SocialMediaMarketing/>
       <BreakDesign/>
       <GraphicDesign/>
       <BreakDesign/>
       <WebDesign/>
       <BreakDesign/>
       <Seo/>
       <BreakDesign/>
       <ContactUs/>
       <BreakDesign/>
       <Experience/>
       <CarouselSlide/>
       <Footer/>
       {/* <DrawerMenu/> */}
      {/* <CarouselSlide /> */}
      {/* <AboutUs/>
      <OurServices/>
      <Footer/> */}
    </Box>
  )
}


// <Text mt={'10px'}>
// In development, expressing stylesheets this way allows your styles to be hot reloaded as you edit them—meaning you can keep application state.In production, all CSS files will be automatically concatenated into a single minified .css file.
// </Text>
// <Text pb={10}>
// In development, expressing stylesheets this way allows your styles to be hot reloaded as you edit them—meaning you can keep application state.In production, all CSS files will be automatically concatenated into a single minified .css file.
// </Text >
// <Link  href='/DigitalMarket'><Text as={'b'}> see all DigitalMarket </Text></Link>